services:
  users:
    build: ./users
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/user-service
      - JWT_SECRET=your_jwt_secret
      - RABBITMQ_URL=amqp://rabbitmq
    depends_on:
      - mongo
      - rabbitmq

  events:
    build: ./events
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/event-service
      - JWT_SECRET=your_jwt_secret
      - RABBITMQ_URL=amqp://rabbitmq
    depends_on:
      - mongo
      - rabbitmq

  registrations:
    build: ./registrations
    ports:
      - "5003:5003"
    environment:
      - MONGO_URI=mongodb://mongo:27017/registration-service
      - JWT_SECRET=your_jwt_secret
      - RABBITMQ_URL=amqp://rabbitmq
    depends_on:
      - mongo
      - rabbitmq

  notifications:
    build: ./notifications
    ports:
      - "5004:5004"
    environment:
      - MONGO_URI=mongodb://mongo:27017/notification-service
      - JWT_SECRET=your_jwt_secret
      - RABBITMQ_URL=amqp://rabbitmq
    depends_on:
      - mongo
      - rabbitmq

  mongo:
    image: mongo
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"     # For services (amqp)
      - "15672:15672"   # Web UI (http://localhost:15672)
